name: Collect Content

on:
  schedule:
    # 06:00 UTC - Morning EU, catches Asia overnight + EU morning
    - cron: '0 6 * * *'
    # 18:00 UTC - Afternoon US, catches US daytime discussions
    - cron: '0 18 * * *'
    # 02:00 UTC - Evening US, catches late US + early Asia
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  collect:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to commit collected data
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for proper git operations
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      
      - name: Install dependencies
        run: uv sync
      
      - name: Run collection
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          HACKERNEWS_ENABLED: true
          GITHUB_TRENDING_ENABLED: true
          MASTODON_ENABLED: true
        run: |
          uv run python -m src.collect
      
      - name: Commit collected data
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/collected_*.json
          if git diff --staged --quiet; then
            echo "No new data collected"
          else
            git commit -m "📥 Collect content - $(date -u +%Y-%m-%d_%H%M%S)"
            git push
          fi
      
      - name: Trigger enrichment workflow
        if: success()
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: collection-complete
